#GET all tasks
GET https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks
Accept: application/json

###
# GET a specific task by ID
GET https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks/1
Accept: application/json

###
#GET a non existent task 
GET https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks/999
Accept: application/json

###
# POST create a new task
POST https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
    "title": "New Task",
    "description": "This is a new task",
    "user_id": 1,
    "completed": false
}

###
# POST task with invalid title
POST https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
    "description": "This task has no title.",
    "user_id": 1,
    "completed": false
}

###

# POST task with invalid user_id
POST https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
    "title": "Task with invalid user_id",
    "description": "This task has an invalid user_id.",
    "user_id": 999,
    "completed": false
}

### 
# PUT update a task
PUT https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks/1
Content-Type: application/json

{
    "title": "Updated Task Title",
    "description": "Updated description",
    "user_id": 1,
    "completed": true
}

### 
# DELETE a task
DELETE https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/tasks/1

### 
# GET all tasks for a specific user
GET https://remote-data-assignment-1-g2bte4gnbyhpdcf9.canadacentral-01.azurewebsites.net/users/1/tasks
Accept: application/json